apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eshop
resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - identity-api.yaml
  - basket-api.yaml
  - catalog-api.yaml
  - ordering-api.yaml
  - order-processor.yaml
  - payment-processor.yaml
  - webhooks-api.yaml
  - webhooksclient.yaml
  - webapp.yaml
  - inference.yaml
