apiVersion: v1
kind: Secret
metadata:
  name: eshop-secrets
  labels:
    app.kubernetes.io/part-of: eshop
stringData:
  postgres-password: postgrespass
  redis-password: redispass
  rabbitmq-password: guest
type: Opaque
